---
apiVersion: helm.fluxcd.io/v1
---
kind: HelmRelease
metadata:
  name: demo
  namespace: demo
  annotations:
    fluxcd.io/tag.comment: semver:~0.1
    fluxcd.io/automated: 'true'
spec:
  releaseName: demo
  chart:
    git: git@github.com:dbaskakov/flux
    ref: master
    path: charts/
  values:
    nginx:
      image:
        repository: nginx
        tag: 1.19.1