---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.0
spec:
  releaseName: nginx
  chart:
    git: git@github.com/dbaskakov/flux
    ref: master
    path: charts/
  values:
      image:
         tag: 1.0.0
