---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "false"
    # fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.2
  values:
    controller:
      config:
        use-forwarded-headers: "true"
        log-format-escape-json: "true"
        log-format-upstream: '{"ts": "$time_iso8601", 
        "http": {"request_id":"$req_id","method":"$request_method","status_code":$status,"url":"$host$request_uri","host":"$host",
        "uri":"$request_uri","request_time":$request_time,"user_agent":"$http_user_agent","protocol":"$server_protocol",
        "trace_session_id":"$http_trace_session_id","server_protocol":"$server_protocol"},
        "nginx": {"x-forward-for":"$proxy_add_x_forwarded_for","remote_addr":"$proxy_protocol_addr","http_referrer":"$http_referer"}}'
      proxySetHeaders: {
        "Trace-Session-Id": "$http_trace_session_id"
      }
      admissionWebhooks:
        enabled: false
      resources:
        requests:
          cpu: 300m
          memory: 150Mi
      metrics:
        port: 10254
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"



