---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/nginx: regex:^1.0.*
    fluxcd.io/tag.chart-image: regex:^1.0.*
spec:
  releaseName: nginx
  chart:
    git: git@github.com:dbaskakov/flux
    ref: master
    path: charts/
  values:
    nginx:
      image:
        repository: impel1o/nginx
        tag: 2.0.0
